### ISSUE TITLE
ユーザ情報のデータベース作成

### ISSUE THREAD

**Issue by imaimai17468** [NUTMEG-hackathon/bibliography_filter#8]
・サーバーを新しく立てなくてもDocker内でデータベースは成り立つのか
→・サーバーたてるのと、Docker内で完結させるのどっちが楽か
・Dockerfileの書き方
・テスト環境と本番環境のdockercomposeの書き方・切り替え方

**Comment by TsubasaOura** [comment]
## Docker内データベース
DockerでDBたてられます。
↓ こんな感じでDB専用コンテナを用意するとOK
```
version: "3"
services:
  db:
    image: mysql:8.0
    container_name: "DB"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
```

## Dockerfileについて
image: mysql って感じでPullするだけで使えるのでDockerfileは書く必要ない
基本は ↓
```
FROM <つかうコンテナ>
WORKDIR <DIR>
RUN <ビルド時に走らせたいコマンド>
```

## テスト本番での使い分け
本番用の別のdocker-composeファイルを作成（たとえば`docker-compose.prod.yml`）して，
```
docker-compose -f docker-compose.prod.yml <sub command>
```
みたいにファイル名を指定することで可能
